name 'quickservice'
maintainer 'Joshua Thornton'
maintainer_email 'jshthornton@gmail.com'
license 'MIT'
description 'Easy service management'
long_description 'Allows actions on services from a quick recipe'
version '0.1.0'
